#!/bin/bash

# Accessibility Testing Script for Nx System Calculator
# This script provides a checklist for manual accessibility testing

echo "🔍 NX SYSTEM CALCULATOR - ACCESSIBILITY TESTING CHECKLIST"
echo "=========================================================="
echo ""

echo "📋 KEYBOARD NAVIGATION TESTS"
echo "----------------------------"
echo "[ ] 1. Press Tab - Skip link should appear and be focused"
echo "[ ] 2. Press Enter on skip link - Should jump to main content"
echo "[ ] 3. Tab through all interactive elements - Should have visible focus indicators"
echo "[ ] 4. Tab to Configuration tab - Press Enter - Should switch tabs"
echo "[ ] 5. Tab to Results tab - Press Space - Should switch tabs"
echo "[ ] 6. Tab to Calculate button - Press Enter - Should trigger calculation"
echo "[ ] 7. Shift+Tab - Should navigate backwards"
echo "[ ] 8. No keyboard traps - Should be able to navigate entire page"
echo ""

echo "🔊 SCREEN READER TESTS"
echo "----------------------"
echo "[ ] 1. Enable screen reader (NVDA/JAWS/VoiceOver)"
echo "[ ] 2. Navigate by landmarks - Should announce banner, main, contentinfo"
echo "[ ] 3. Navigate by headings - Should have proper hierarchy (H1 > H2 > H3)"
echo "[ ] 4. Navigate by form fields - All inputs should have labels"
echo "[ ] 5. Required fields - Should announce 'required'"
echo "[ ] 6. Error messages - Should be announced when they appear"
echo "[ ] 7. Tab navigation - Should announce tab role and selected state"
echo "[ ] 8. Loading states - Should announce 'busy' when calculating"
echo "[ ] 9. Results - Should announce when results are available"
echo ""

echo "🎨 VISUAL ACCESSIBILITY TESTS"
echo "-----------------------------"
echo "[ ] 1. Zoom to 200% - Content should remain readable and usable"
echo "[ ] 2. Check color contrast - Use browser DevTools or contrast checker"
echo "[ ] 3. High contrast mode - Enable system high contrast mode"
echo "[ ] 4. Focus indicators - Should be clearly visible on all elements"
echo "[ ] 5. Error states - Should use icons + color + text"
echo "[ ] 6. Required fields - Should have visual and semantic indicators"
echo ""

echo "📱 RESPONSIVE DESIGN TESTS"
echo "--------------------------"
echo "[ ] 1. Mobile (320px) - All content should be readable and usable"
echo "[ ] 2. Mobile (375px) - iPhone size, test touch targets"
echo "[ ] 3. Tablet (768px) - Layout should adapt appropriately"
echo "[ ] 4. Desktop (1024px) - Full desktop layout"
echo "[ ] 5. Large desktop (1920px) - Content should not be too wide"
echo "[ ] 6. Touch targets - All interactive elements should be 44x44px minimum"
echo "[ ] 7. Text size - Minimum 16px to prevent iOS zoom"
echo "[ ] 8. Orientation - Test both portrait and landscape"
echo ""

echo "🎯 FORM ACCESSIBILITY TESTS"
echo "---------------------------"
echo "[ ] 1. All inputs have labels - Click label should focus input"
echo "[ ] 2. Required fields - Marked with * and aria-required"
echo "[ ] 3. Error messages - Linked to inputs via aria-describedby"
echo "[ ] 4. Autocomplete - Email and company fields have autocomplete"
echo "[ ] 5. Character counter - Description field shows character count"
echo "[ ] 6. Validation - Real-time validation with accessible feedback"
echo "[ ] 7. Submit without filling - Should show accessible error messages"
echo ""

echo "🎬 MOTION AND ANIMATION TESTS"
echo "-----------------------------"
echo "[ ] 1. Enable 'Reduce motion' in system preferences"
echo "[ ] 2. Animations should be minimal or disabled"
echo "[ ] 3. Loading spinner should still be visible but not animated"
echo "[ ] 4. Transitions should be instant or very brief"
echo ""

echo "🔧 AUTOMATED TESTING TOOLS"
echo "--------------------------"
echo "Run these automated tests:"
echo ""
echo "1. axe DevTools (Browser Extension):"
echo "   - Install axe DevTools extension"
echo "   - Open DevTools > axe DevTools tab"
echo "   - Click 'Scan ALL of my page'"
echo "   - Review and fix any violations"
echo ""
echo "2. Lighthouse (Chrome DevTools):"
echo "   - Open DevTools > Lighthouse tab"
echo "   - Select 'Accessibility' category"
echo "   - Click 'Generate report'"
echo "   - Aim for 100% score"
echo ""
echo "3. WAVE (Browser Extension):"
echo "   - Install WAVE extension"
echo "   - Click WAVE icon"
echo "   - Review errors, alerts, and features"
echo ""
echo "4. Keyboard Navigation Test:"
echo "   - Unplug mouse"
echo "   - Navigate entire application using only keyboard"
echo "   - All functionality should be accessible"
echo ""

echo "📊 TESTING CHECKLIST SUMMARY"
echo "----------------------------"
echo "Total Tests: 40+"
echo ""
echo "Categories:"
echo "  - Keyboard Navigation: 8 tests"
echo "  - Screen Reader: 9 tests"
echo "  - Visual Accessibility: 6 tests"
echo "  - Responsive Design: 8 tests"
echo "  - Form Accessibility: 7 tests"
echo "  - Motion/Animation: 4 tests"
echo "  - Automated Tools: 4 tools"
echo ""

echo "🎯 WCAG 2.1 LEVEL AA COMPLIANCE"
echo "-------------------------------"
echo "Principle 1: Perceivable"
echo "  [ ] 1.1 Text Alternatives"
echo "  [ ] 1.3 Adaptable"
echo "  [ ] 1.4 Distinguishable"
echo ""
echo "Principle 2: Operable"
echo "  [ ] 2.1 Keyboard Accessible"
echo "  [ ] 2.4 Navigable"
echo "  [ ] 2.5 Input Modalities"
echo ""
echo "Principle 3: Understandable"
echo "  [ ] 3.1 Readable"
echo "  [ ] 3.2 Predictable"
echo "  [ ] 3.3 Input Assistance"
echo ""
echo "Principle 4: Robust"
echo "  [ ] 4.1 Compatible"
echo ""

echo "✅ QUICK START TESTING"
echo "---------------------"
echo "1. Start the development server:"
echo "   cd frontend && npm run dev"
echo ""
echo "2. Open browser to http://localhost:5173"
echo ""
echo "3. Run automated tests:"
echo "   - Open DevTools (F12)"
echo "   - Run Lighthouse accessibility audit"
echo "   - Install and run axe DevTools"
echo ""
echo "4. Manual keyboard test:"
echo "   - Press Tab repeatedly"
echo "   - Verify all interactive elements are reachable"
echo "   - Verify focus indicators are visible"
echo ""
echo "5. Screen reader test:"
echo "   - Enable VoiceOver (macOS): Cmd+F5"
echo "   - Enable NVDA (Windows): Download from nvaccess.org"
echo "   - Navigate the page and verify announcements"
echo ""

echo "📚 RESOURCES"
echo "------------"
echo "- WCAG 2.1 Guidelines: https://www.w3.org/WAI/WCAG21/quickref/"
echo "- WebAIM: https://webaim.org/"
echo "- A11y Project: https://www.a11yproject.com/"
echo "- MDN Accessibility: https://developer.mozilla.org/en-US/docs/Web/Accessibility"
echo ""

echo "=========================================================="
echo "✅ Accessibility testing checklist ready!"
echo "=========================================================="

